"""empty message

Revision ID: 31b5ee0b3d1e
Revises: 54a650fe05e5
Create Date: 2015-03-04 18:55:36.621952

"""

# revision identifiers, used by Alembic.
revision = '31b5ee0b3d1e'
down_revision = '54a650fe05e5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save_extension')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_extension',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('urls', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('explain', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tag', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
