"""empty message

Revision ID: 54a650fe05e5
Revises: 43e32ff4325d
Create Date: 2015-02-24 15:15:08.812533

"""

# revision identifiers, used by Alembic.
revision = '54a650fe05e5'
down_revision = '43e32ff4325d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('urls', sa.String(length=255), nullable=True),
    sa.Column('explain', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save_extension')
    ### end Alembic commands ###
